### ISSUE TITLE
Utils tests cannot properly connect to ASpace as configured

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/ArchivesSnake#13]
`FAILED tests/test_utils.py::TestDataHelpers::test_closest_value - requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8089)`

Utils tests require logging into AS, and as written, they cannot with the current settings.

**Comment by p-galligan** [comment]
Getting a different error now, since I made sure all the correct cassettes were available.

`FAILED tests/test_utils.py::TestDataHelpers::test_closest_value - TypeError: closest_value() missing 1 required positional argument: 'client'`
`FAILED tests/test_utils.py::TestDataHelpers::test_get_orphans - vcr.errors.CannotOverwriteExistingCassetteException: Can't overwrite existing cassette ('tests/fixtures/cassettes/test_get_orphans.json')`

**Comment by p-galligan** [comment]
@helrond I'm not sure what's up with the missing client argument error. Do you have any insight into why that might be happening here?

We haven't changed any tests or data helpers that would set that value.

**Comment by helrond** [comment]
@p-galligan well `closest_value` takes three arguments and it's only being passed two in the test, so I'd start there.

**Comment by p-galligan** [comment]
Some more information about the VCR errors that I'm running into.

`self = <vcr.patch.VCRRequestsHTTPConnectiontests/fixtures/cassettes/test_get_orphans.json object at 0x10e519090>, _ = False, kwargs = {'buffering': True}

    def getresponse(self, _=False, **kwargs):
        """Retrieve the response"""
        # Check to see if the cassette has a response for this request. If so,
        # then return it
        if self.cassette.can_play_response_for(self._vcr_request):
            log.info("Playing response for {} from cassette".format(self._vcr_request))
            response = self.cassette.play_response(self._vcr_request)
            return VCRHTTPResponse(response)
        else:
            if self.cassette.write_protected and self.cassette.filter_request(self._vcr_request):
                raise CannotOverwriteExistingCassetteException(
>                   cassette=self.cassette, failed_request=self._vcr_request
                )
E               vcr.errors.CannotOverwriteExistingCassetteException: Can't overwrite existing cassette ('tests/fixtures/cassettes/test_get_orphans.json') in your current record mode ('once').
E               No match for the request (<Request (GET) http://localhost:8089/repositories/2/archival_objects/json?page_size=100&page=1>) was found.
E               Found 28 similar requests with 1 different matcher(s) :
E               
E               1 - (<Request (GET) http://localhost:8089/version>).
E               Matchers succeeded : ['method']
E               Matchers failed :
E               path - assertion failure :
E               /repositories/2/archival_objects/json != /version`

**Comment by helrond** [comment]
Look at this URL: `http://localhost:8089/repositories/2/archival_objects/json?page_size=100&page=1` - that doesn't look like a real AS URL.

**Comment by p-galligan** [comment]
After some testing, this issue is getting raised when we call `orphans = utils.get_orphans(archival_objects, "linked_agents")` on lines 108-109.

The jsonify decorator is causing problems because the tests and functions work based off of a JSONModelObject, but obviously that decorator has changed from what it used to do.

**Comment by helrond** [comment]
So I think what would have to happen here is to tweak the test so it doesn't use a JSONModel object, and then possibly recut the VCR cassette. 

I'd propose closing this issue in favor of #17 since recutting tweaking the test/recutting the cassette is part of that work. How does that sound @p-galligan?

**Comment by p-galligan** [comment]
Sounds good to me.
