### ISSUE TITLE
Review docstring formatting

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/ArchivesSnake#14]
Compare RAC docstrings with existing ArchivesSnake docstrings to ensure they will generate uniform documentation. A couple of things I'm noticing:

- ArchivesSnake docstrings don't have leading whitespace on secondary lines
- RAC docstrings tend to use structured elements to describe arguments and return values.

My main concern is simply that the autodocs are properly generated. If we identify additional pieces of work (like adding more  structured elements to existing docstrings) we should file that as a separate issue (and one which will need conversation with the rest of the ArchivesSnake contributors).

**Comment by a-berish** [comment]
Leading whitespace does not seem to impact the generation of the documentation. We have decided to leave the structured elements that exist in our docstrings (like args and returns) for now, awaiting a broader discussion between our team and Asnake contributors about Asnake documentation styling and content.
